{{- if .Values.global.ingress.enabled }}
{{- range $name, $svc := .Values.services }}
{{- if and $svc.enabled $svc.ingress }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $name }}
  annotations:
    {{- toYaml $.Values.global.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ $.Values.global.ingress.className }}
  tls:
    - hosts: [{{ $.Values.global.ingress.host | quote }}]
      secretName: {{ $.Values.global.ingress.tlsSecret }}
  rules:
    - host: {{ $.Values.global.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $name }}
                port:
                  name: http
{{- end }}
{{- end }}
{{- end }}
